name: Deploy to Dev Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH client
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy app
        run: |
          echo "Deploying app"
          rm -rf .git*
          ssh -o StrictHostKeyChecking=no ubuntu@16.171.135.165 "mkdir -p /tmp/app ; mkdir -p /var/www/sms-crms-supra"
          tar -czf - . | ssh -o StrictHostKeyChecking=no ubuntu@16.171.135.165 "tar -xzf - -C /tmp/app"
          ssh -o StrictHostKeyChecking=no ubuntu@16.171.135.165 "rm -rf /var/www/sms-crms-supra/* ; rm -rf /var/www/sms-crms-supra/.* ; cp -r /tmp/app/. /var/www/sms-crms-supra/ ; rm -rf /tmp/app;"
